### PR TITLE
Fix https://github.com/sanic-org/sanic/issues/2106

### PR DESCRIPTION
**Pull request by artcg**
#2106

### CODE REVIEW

**Comment by sjsadowski** [comment]
@artcg can you add a test so we can prevent reversions? Thanks!

**Review by ashleysommer — CHANGES_REQUESTED** [review]
Looks great to me!
Just needs a test added, and we can merge it.

**Comment by artcg** [comment]
Should I also open PR against 20.12LTS / 19.12LTS branch? Not sure how you handle those releases

**Comment by ahopkins** [comment]
Please update the title for this PR to something more descriptive. I use these when generating the change logs.

**Review by ahopkins — CHANGES_REQUESTED** [review]
Once you update the title we can merge. Also, this is probably a bug worth doing for the LTS branches as you mentioned. Separate PRs for each. Although I do not think we need to release them before the June release unless something more pressing comes up.

**Comment by artcg** [comment]
Somehow if this isnt going to be released im not inspired to continue to make changes on it

**Comment by ahopkins** [comment]
@artcg I am very disappointed to hear that. And, quite frankly stunned by that position. I did not say it was not going to be released. Of course, everything merged will be. However, seeing as this is something that has been in the code base over two years, I do not see the need to push out a bug fix release to 19.12 and 18.12 before the June release date. If I am wrong, I would expect you to engage in a civil debate rather than sacking the whole PR. Indeed, I shall repeat myself: I am very disappointed to hear that.

**Comment by artcg** [comment]
I dont really enjoy debating though just investigated this issue since it is blocking my workplace from updating sanic from 18.12 to 20.12 and i thought it would be cleaner to fix the source than to do a workaround on the client code end

also coding is not something i do for fun, it is just a means to make a living, if the code i write wont be deployed, whats the use? I struggle to have enough time with my hobbies as it is

**Comment by sjsadowski** [comment]
I'll shepherd this through and create a new PR; I cloned the forked repo and will drop a new branch for that to see if we can get it across the finish line for at least 21.6 and 20.12LTS. I'm pretty heavily loaded with not-sanic work so I may need some help once the branch is up to get it merged for the LTS.

**Comment by artcg** [comment]
Thanks for taking this over @sjsadowski, I have apologised to Adam for my behaviour here.

**Comment by sjsadowski** [comment]
@artcg I have a bunch of competing priorities this week, if you're up for getting the PRs for 20.12LTS and 19.12LTS is would be really helpful

**Comment by artcg** [comment]
Yes sure can do that, no need for a release also not sure why I even wanted that so much

**Pull request closed without merging**
