### PR TITLE
Sanic routing

### PR DESCRIPTION
**Pull request by ahopkins**
Implementation of [sanic-routing](https://github.com/sanic-org/sanic-router). Currently, it is written as a dependency. Whether it stays that way or is merged into this repo is up for discussion at a later date.

Besides overhauling the Router to use the compiled version, this also hits the following:

- Resolve bug with middleware in Blueprint Group when passed callable
- Moves common logic between `Blueprint` and `Sanic` into mixins
- Will ~likely~ touch on some consistency with naming of routes, ~I am divided on this but if we are going to break it, then we should do it now~
- Some new convenience decorators:
    - `@app.before_server_start`
    - `@app.after_server_start`
    - `@app.before_server_stop`
    - `@app.after_server_stop`
    - `@app.on_request`
    - `@app.on_response`
- fixes `Allow` header that did not include `HEAD`
- using "name" keyword in url_for for a "static" route where name does not exist
- Cannot have multiple app.static() without using the named param
- using "filename" keyword in url_for on a file route
- request endpoint is the route name, should mark that as deprecated
- route names are fully namespaced
- no handler type name prefixes (static, websocket, etc)
- unquote in route def (not automatic)
- routes_all is tuples
- handler arguments are kwarg only
- `request.match_info` is now a cached (and not computed) property
- unknown static file mimetype is sent as `application/octet-stream`
- `_host` keyword in `url_for`
- add charset default to utf-8 for text and js content types if not specified
- versionfor a route can be `str`, `float`, or `int`
- route has `ctx` property
- app has `routes_static`, `routes_dynamic`, `routes_regex`

[See discussion](https://community.sanicframework.org/t/a-fast-new-router/649)

### CODE REVIEW

**Comment by ahopkins** [comment]
This pull request has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/a-fast-new-router/649/38

**Comment by ashleysommer** [comment]
Looking great!

**Comment by ahopkins** [comment]
Requires: https://github.com/sanic-org/sanic-testing/pull/13

**Comment by ahopkins** [comment]
Relies upon:
- https://pypi.org/project/sanic-routing/0.1.0/
- https://pypi.org/project/sanic-testing/0.3.0/

**Comment by ahopkins** [comment]
Passing tests except for Python 3.6 with uvloop. See #2024

**Comment by ahopkins** [comment]
Fixes #1671

**Review by ashleysommer — APPROVED** [review]
Looking great

**Pull request merged**
