### PR TITLE
Always show server location in ASGI

### LINKED ISSUE #2520: uvicorn (ASGI?) unable to run sanic application
**Describe the bug**
Sanic used to work behind uvicorn (ASGI). Now I can't get it to work

**Code snippet**

```python
# test_app.py
from sanic import Sanic, response


app = Sanic(name="test")


@app.get("/")
async def index(request):
    return response.text("ok")
```

```console
$ uvicorn test_app:app
```

uvicorn+sanic then launches with:

```
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```
but on first request there's a 500 like:

```Traceback (most recent call last):
  File "/home/pagessin/dev/sentinel/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pagessin/dev/sentinel/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/pagessin/dev/sentinel/.venv/lib/python3.10/site-packages/sanic/app.py", line 1297, in __call__
    self._asgi_app = await ASGIApp.create(self, scope, receive, send)
  File "/home/pagessin/dev/sentinel/.venv/lib/python3.10/site-packages/sanic/asgi.py", line 167, in create
    await sanic_app.dispatch(
  File "/home/pagessin/dev/sentinel/.venv/lib/python3.10/site-packages/sanic/signals.py", line 193, in dispatch
    return await dispatch
  File "/home/pagessin/dev/sentinel/.venv/lib/python3.10/site-packages/sanic/signals.py", line 131, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/home/pagessin/dev/sentinel/.venv/lib/python3.10/site-packages/sanic/signals.py", line 93, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
INFO:     127.0.0.1:33318 - "GET /status HTTP/1.1" 500 Internal Server Error
```

**Expected behavior**
Sanic is able to respond to HTTP requests via ASGI.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - `sanic==22.6.1`
 - `uvicorn==0.18.2`

**Additional context**

### PR DESCRIPTION
**Pull request by ahopkins**
Closes #2520 

Co-authored-by: Adam Hopkins <adam@amhopkins.com>
Co-authored-by: Zhiwei Liang <zhi.wei.liang@outlook.com>

### CODE REVIEW

**Comment by ChihweiLHBird** [comment]
Our CI is broken?

**Comment by ahopkins** [comment]
Or our testing on this is not sufficient. But I thought we had ASGI lifespan triggers tested.

**Comment by ChihweiLHBird** [comment]
```
type-checking run-test-pre: PYTHONHASHSEED='3170477258'
type-checking run-test: commands[0] | mypy sanic
sanic/app.py:1317: error: Signature of "asgi" incompatible with supertype "RunnerMixin"
Found 1 error in 1 file (checked 83 source files)
ERROR: InvocationError for command /home/chihwei/sanic/.tox/type-checking/bin/mypy sanic (exited with code 1)
____________________________________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________________________________
ERROR:   type-checking: commands failed
```

Can you also try to close and reopen this PR to see if we can trigger the CI?

**Comment by ahopkins** [comment]
Will when I push some tests. It just didn't because it was originally changing targets. That doesn't trigger.

**Comment by azimovMichael** [comment]
Is there any solution for this in the meantime? Or just stay with 22.3 version?

**Comment by ahopkins** [comment]
Will be releasing this probably tomorrow if that helps.

**Pull request merged**
