### PR TITLE
Fix `test_cli` and `test_cookies`

### PR DESCRIPTION
**Pull request by ChihweiLHBird**
I was able to reproduce the test cli issues on my laptop, which is the timeout occurred when running the subprocess in `capture` function. After increasing the timeout locally, the issue never came up again during multiple tests.

Open this PR to further test the test cases.

I think this issue usually happen on smaller machine with lower performance.

### CODE REVIEW

**Comment by ChihweiLHBird** [comment]
Test cookies issue seems a problem of httpx's async client. 
https://github.com/encode/httpx/discussions/2144

In the failed test cookie case, the headers contain setting cookie but hpptx didn't put it into `response.cookies`. I think there is not much we can do until httpx dev team fix it. If we really want to fix it right now, we can try to parse the cookies in sanic-testing after getting the response object from httpx.

**Review by ahopkins — DISMISSED** [review]

**Comment by ChihweiLHBird** [comment]
It's weird that fixing cli tests seems increase the chance of the failed cookies test. @ahopkins

**Comment by ChihweiLHBird** [comment]
The cookies test fixed, the only (occasionally) broken test case is keep alive.

**Review by ahopkins — APPROVED** [review]

**Comment by ahopkins** [comment]
Amazing amazing work. You rock.

**Pull request merged**
