### PR TITLE
Prepare for 21.3 release

### PR DESCRIPTION
**Pull request by ahopkins**
Waiting on #2042, #2053, #2055.

Includes changelog, some updates to the RTD templates, and bump version.

### CODE REVIEW

**Review by harshanarayana — DISMISSED** [review]

**Comment by harshanarayana** [comment]
#2053, #2055 would be added to this list + signals when you merge them right ?

**Comment by ahopkins** [comment]
Yup.

**Review by yunstanford — APPROVED** [review]

**Comment by ashleysommer** [comment]
Late notice, but can we include https://github.com/sanic-org/sanic/pull/2059 too?

**Comment by ashleysommer** [comment]
Still needs #2042, #2053, #2055 descriptions added to the list

**Comment by ahopkins** [comment]
> Still needs #2042, #2053, #2055 descriptions added to the list

Yup, that commit is coming soon.

**Review by ashleysommer — APPROVED** [review]

**Review by ashleysommer — APPROVED** [review]

**Pull request merged**
