### PR TITLE
Add one type hint for `protocol`

### PR DESCRIPTION
**Pull request by ChihweiLHBird**
Found it was helpful when debugging this issue: https://github.com/sanic-org/sanic/issues/2177

### CODE REVIEW

**Review by ahopkins — APPROVED** [review]

**Comment by ChihweiLHBird** [comment]
Although the type check failed, this new added type hint is the type of that object. I printed the type when running it. I am not sure why mypy gave these errors...

```
chihwei@MyMachine:~/sanic$ tox -e type-checking
type-checking develop-inst-nodeps: /home/chihwei/sanic
type-checking installed: aiofiles==0.7.0,httptools==0.2.0,multidict==5.1.0,mypy==0.910,mypy-extensions==0.4.3,-e git+https://github.com/ChihweiLHBird/sanic@2d22b93248a5767774351b060f39f1bb7a255298#egg=sanic,sanic-routing==0.7.0,toml==0.10.2,types-ujson==0.1.1,typing-extensions==3.10.0.0,ujson==4.0.2,uvloop==0.15.2,websockets==9.1
type-checking run-test-pre: PYTHONHASHSEED='3048533415'
type-checking run-test: commands[0] | mypy sanic
sanic/http.py:104: error: Cannot determine type of "request_max_size"
sanic/http.py:107: error: Incompatible types in assignment (expression has type "None", variable has type "Request")
sanic/http.py:108: error: Incompatible types in assignment (expression has type "None", variable has type "BaseHTTPResponse")
sanic/http.py:333: error: Cannot determine type of "access_log"
sanic/http.py:416: error: Cannot determine type of "request_class"
sanic/http.py:417: error: "None" has no attribute "encode"
sanic/http.py:501: error: Incompatible types in assignment (expression has type "int", variable has type "None")
sanic/http.py:502: error: Unsupported operand types for + ("None" and "int")
sanic/http.py:502: error: Incompatible types in assignment (expression has type "int", variable has type "None")
Found 9 errors in 1 file (checked 41 source files)
```

**Comment by ahopkins** [comment]
I'll pull locally and check 🤔

**Comment by ChihweiLHBird** [comment]
> I'll pull locally and check 🤔

I feel like mypy is too strict when dealing with None value 😂

**Comment by ahopkins** [comment]
I am closing this. If there are some annotations that we want, open a new PR. But, we are not going to be messing with `Http` loop right now.

**Pull request closed without merging**
