### PR TITLE
add eof method to close stream

### LINKED ISSUE #2067: New style streaming route handler improvements
**Is your feature request related to a problem? Please describe.**
The new streaming API allows streaming responses in the route handler without having to use a callback:

```python
@app.route("/")
async def test(request):
    response = await request.respond(content_type="text/csv")
    await response.send("foo,")
    await response.send("bar")
    await response.send("", True)
    return response
```

**Describe the solution you'd like**
A simpler method to closing the stream before returning in place of `await response.send("", True)`

```python
await response.eof()
```

Under the hood, `eof` should simply just be a convenience call to `send("", True)`.

### PR DESCRIPTION
**Pull request by ajaygupta2790**
Resolves #2067

### CODE REVIEW

**Review by ahopkins — CHANGES_REQUESTED** [review]
Looks good. Can you add some tests that utilize the new style streaming response?

I would maybe look in `tests/test_response.py` at one of the `streaming_app` tests and use those as a starting point.

**Comment by sjsadowski** [comment]
@ajaygupta2790 Are you able to add tests for this?

**Comment by ajaygupta2790** [comment]
@sjsadowski @ahopkins No, I am not able to added cases yet. I am having difficulty understanding the existing ones and make changes

**Comment by ahopkins** [comment]
No worries. I can do it :sunglasses: 

Thanks for the PR.

**Review by ahopkins — APPROVED** [review]

**Comment by ajaygupta2790** [comment]
I was clearly using the wrong approach for this, will help in future PRs :)

**Pull request merged**
