### PR TITLE
Fixed: CI Runs on Ready PRs Only

### PR DESCRIPTION
**Pull request by ChihweiLHBird**
Reverts sanic-org/sanic#2311

Will test some community's idea: https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/17

### CODE REVIEW

**Comment by ChihweiLHBird** [comment]
https://github.com/ChihweiLHBird/Test/pulls

Sample trials seems successful, will try to move code to here:
https://github.com/ChihweiLHBird/Test/pulls

**Comment by ahopkins** [comment]
We need to get this back in. Did you have another solution for ignoring drafts, but allowing pushes on all other regular PRs to work as expected?

**Comment by ChihweiLHBird** [comment]
@ahopkins Yes, for draft the tests skipped but shows successful. Do you think that's suitable for our community?

https://github.com/ChihweiLHBird/Test/pull/3

image

**Comment by ahopkins** [comment]
> @ahopkins Yes, for draft the tests skipped but shows successful. Do you think that's suitable for our community? You can also try to convert this PR to draft to see the effect.

Yes. Only the current Release Managers have the ability to merge into `main`, so that is okay.

**Comment by ChihweiLHBird** [comment]
> > @ahopkins Yes, for draft the tests skipped but shows successful. Do you think that's suitable for our community? You can also try to convert this PR to draft to see the effect.
> 
> Yes. Only the current Release Managers have the ability to merge into `main`, so that is okay.

Thanks Adam, and I think this PR is ready. Can you help me to review it? Thanks!

By the way, it seems our testing is not very reliable yet, so maybe we can try to fix it to prevent confusion. 😂

**Review by ahopkins — APPROVED** [review]

**Comment by ahopkins** [comment]
> By the way, it seems our testing is not very reliable yet, so maybe we can try to fix it to prevent confusion. joy

It seems there was a change to the base images and some of the tests that rely upon recycling ports sometimes get caught in race conditions. We need to probably just give them a few more seconds in CI, or (probably better approach) move them to unique ports and try to make the tests themselves less flappy. Locally I have no problem whatsoever. It is one of those issues I always forget to work on locally, but should not take much effort.

**Pull request merged**
