### PR TITLE
Upgrade httpx (to 0.16.1) and httpcore (to 0.12.2)

### PR DESCRIPTION
**Pull request by drgarcia1986**
Hi guys 
I wanna use sanic with httpx on my project (both in the last version).

### CODE REVIEW

**Comment by drgarcia1986** [comment]
`AppVeyor` build failed, is it an issue with windows?

**Comment by ahopkins** [comment]
I'm looking on my phone, and I see this

> The specified network name is no longer available

**Comment by drgarcia1986** [comment]
@ahopkins thank you!
Where you found this?

**Comment by ahopkins** [comment]
> @ahopkins thank you!
> Where you found this?

https://ci.appveyor.com/project/sjsadowski/sanic/builds/36490207/job/lssrj4ig674if5eq#L208

**Comment by drgarcia1986** [comment]
Man what stranger error 🤔 https://stackoverflow.com/questions/59326649/how-to-avoid-connectionreseterror

**Comment by ahopkins** [comment]
I restarted the job. Maybe it's a transient build error.

**Comment by drgarcia1986** [comment]
same error 😞 
I'll investigate, thank you @ahopkins

**Comment by ahopkins** [comment]
Ping @drgarcia1986 

Any luck? I would love to get this into the next release.

**Comment by drgarcia1986** [comment]
Hi @ahopkins sorry for the delay.
No, I can't found the root cause

**Comment by ahopkins** [comment]
@drgarcia1986 Thanks for checking. I am going to ping the `httpx` team and see if they have seen anything like this before.

**Comment by ahopkins** [comment]
Closing this since we are removing httpx in next release. See #1850

**Pull request closed without merging**
