### PR TITLE
Handle case when `headers` argument of `ResponseStream` constructor is `None`

### PR DESCRIPTION
**Pull request by liamcoatman**
The default value for the `headers` argument is `None`. This leads to an Exception when `headers` is passed to the `Header` constructor, which is expecting a Mapping type.

### CODE REVIEW

**Comment by liamcoatman** [comment]
@ahopkins I've added a test, which was failing prior to my fix and is now passing. I've probably put it in the wrong place, so let me know if you want me to move it.

**Comment by ahopkins** [comment]
It's a long file, but I'd dump it here: https://github.com/sanic-org/sanic/blob/main/tests/test_response.py

**Comment by liamcoatman** [comment]
In case you missed it, I moved the test to `test_response.py` as suggested

**Comment by QylinFly** [comment]
ResponseStream is not stream,bug?

**Comment by ahopkins** [comment]
> ResponseStream is not stream,bug?

Sorry, I don't understand your question.

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
