### PR TITLE
Fix uvloop 1912

### PR DESCRIPTION
**Pull request by ahopkins**
Related to #2024

### CODE REVIEW

**Review by ashleysommer — APPROVED** [review]

**Comment by ashleysommer** [comment]
Strange dependency issue happening in this branch now.
Something is causing MultiDict==5.1.0 to be installed, but this version of Sanic is pinned MultiDict==5.0.0 causing a PIP install error.

**Comment by ashleysommer** [comment]
Another oddity I found while trying to debug that conflict above:
```
ERROR: Cannot install chardet<=2.3.0 and httpcore==0.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested chardet<=2.3.0
    httpcore 0.3.0 depends on chardet==3.*
```

**Comment by ashleysommer** [comment]
Created https://github.com/sanic-org/sanic/pull/2027 to fix the TOX requirement install issues.
Merge #2027 then resync to #2025 and re-run the tests.

**Comment by ahopkins** [comment]
All good :sunglasses:

**Pull request merged**
