### PR TITLE
Don't try to send a response if the request was cancelled and the transport has been cleaned out

### LINKED ISSUE #2186: Exception when terminating while receiving a request
**Describe the bug**
Chrome, Safari and probably other browsers seem to open surplus connections to the server in advance in order to improve performance (see for example [this stackoverflow thread](https://stackoverflow.com/questions/4761913/server-socket-receives-2-http-requests-when-i-send-from-chrome-and-receives-one)). These connections are kept open in the state "wait for request".

If Sanic is terminated with such a pending request, the request gets cancelled after `GRACEFUL_SHUTDOWN_TIMEOUT` and the receive is cancelled. In reaction the the `CancelledError`, Sanic will try to send an error response, but the transport has already been cleaned out, and as the request has not been received yet a new empty, request with `transport=None` is created. The symptom is this trace:

```
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/http.py", line 126, in http1
    await self.http1_request_header()
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/http.py", line 188, in http1_request_header
    await self._receive_more()
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/server.py", line 222, in receive_more
    await self._data_received.wait()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/server.py", line 197, in connection_task
    await self._http.http1()
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/http.py", line 142, in http1
    await self.error_response(e)
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/http.py", line 405, in error_response
    await app.handle_exception(self.request, exception)
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/app.py", line 704, in handle_exception
    await response.send(end_stream=True)
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/response.py", line 122, in send
    await self.stream.send(data, end_stream=end_stream)
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/http.py", line 335, in http1_response_header
    await self._send(ret)
  File "/Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/server.py", line 267, in send
    if self.transport.is_closing():
AttributeError: 'NoneType' object has no attribute 'is_closing'
``` 

**Code snippet**
This can be reproduced with the hello world example. Load the page in Chrome, then terminate. Sanic will wait 15 seconds, then die with above trace. On my Mac, this happens about 75% of the time.

**Expected behavior**
Clean exit.

**Environment (please complete the following information):**
 - OS: MacOS
 - Version: 21.6.0

### PR DESCRIPTION
**Pull request by DirtyHairy**
Fixes #2186

### CODE REVIEW

**Comment by Tronic** [comment]
Thanks for the PR! The change seems necessary but I wonder if this is fixing a special case rather than the more general problem of trying to respond to a closed transport. Perhaps the http1 handler should just return immediately once the transport is closed (which is supposed to happen when the task is canceled). I won't be able to look at this right now to see which is the best way to handle it but just bringing up this point for conversation.

**Comment by DirtyHairy** [comment]
@Tronic I don't know the codebase well enough to really judge, but what you are saying makes sense to me. I also wasn't sure whether this is the best place to fix it, but it seemed good enough to fix my issue 😏 When I find time I can dig a bit deeper into the codebase to handle this more properly.

**Comment by ahopkins** [comment]
@DirtyHairy @Tronic Are either of you looking at this further?

**Comment by DirtyHairy** [comment]
@ahopkins See my comment on #2191 , not at this time, sorry.

**Comment by ahopkins** [comment]
CLosing in favor of #2245

**Pull request closed without merging**
