### PR TITLE
Remove Duplicated Dependencies and PEP 517 Support

### PR DESCRIPTION
**Pull request by ChihweiLHBird**
1. Many dependencies are in `requirements` but also in `extras_require`. So I think we can remove them from `extras_require`.
2. Add `pyproject.toml`, which is the "file be used to specify what program to use for generating distribution."
https://setuptools.readthedocs.io/en/latest/build_meta.html

### CODE REVIEW

**Comment by ahopkins** [comment]
A route I think I'd rather go down is to have some requirements files and read them into setup.py and tox.ini instead of duplicating them. Do you want to have a run at that?

**Comment by ChihweiLHBird** [comment]
> A route I think I'd rather go down is to have some requirements files and read them into setup.py and tox.ini instead of duplicating them. Do you want to have a run at that?

How about put the requirements into the `setup.cfg` file instead of the `requirements.txt` file? Do you think is a good idea?

**Comment by ahopkins** [comment]
I'm not opposed. Any organization effort would be better.

**Comment by ChihweiLHBird** [comment]
> I'm not opposed. Any organization effort would be better.

@ahopkins 
I checked it, and it appears that we have dynamic dependencies manipulation (line 124-137) in `setup.py`, maybe leaving the requirements in `setup.py` is reasonable, because what we will put into the `requirements.txt` or `setup.cfg`, is not finalized requirements list. What do you think?

**Comment by ahopkins** [comment]
I would do something like this in `setup.py`:

```python
allow_uvloop = see_existing_setup_py
allow_ujson = see_existing_setup_py

filters = (
    lambda x: x.startswith("#"),
    lambda x: x.startswith("uvloop") if not allow_uvloop else False,
    lambda x: x.startswith("ujson") if not allow_ujson else False,
)
def load_requirements(path_to_reqs):
    with open(path_to_reqs, "r") as f:
        reqs = [req.strip() for req in f.readlines() if not any(f(r) for f in filters)]
    return reqs

load_requirements("./requirements.txt")
```

**Comment by ChihweiLHBird** [comment]
> I would do something like this in `setup.py`:
> 
> ```python
> allow_uvloop = see_existing_setup_py
> allow_ujson = see_existing_setup_py
> 
> filters = (
>     lambda x: x.startswith("#"),
>     lambda x: x.startswith("uvloop") if not allow_uvloop else False,
>     lambda x: x.startswith("ujson") if not allow_ujson else False,
> )
> def load_requirements(path_to_reqs):
>     with open(path_to_reqs, "r") as f:
>         reqs = [req.strip() for req in f.readlines() if not any(f(r) for f in filters)]
>     return reqs
> 
> load_requirements("./requirements.txt")
> ```

I think manually parse requirements.txt is okay if we don't have those extra requirements for tests, dev, and docs, but things get complicated since we have them. And the `parse_requirements` API by pip is now an internal API and we probably want to avoid using it. I tried `pkg_resources.parse_requirements` by setuptools but it does not parse `sys_platform != win32` in my requirements.txt. So I would suggest using our current pattern of requirements list in `setup.py`.


**requirements.txt**
```
ujson>=1.35; sys_platform != win32 and implementation_name == cpython
uvloop>=0.5.3; sys_platform != win32 and implementation_name == cpython
sanic-routing==0.7.0rc1
httptools>=0.0.10
aiofiles>=0.6.0
websockets>=9.0
multidict>=5.0<6.0
sanic-testing[dev,test]>=0.6.0
pytest[dev,test]==5.2.1
gunicorn[dev,test]==20.0.4
pytest-cov[dev,test]
beautifulsoup4[dev,test]
pytest-sanic[dev,test]
pytest-sugar[dev,test]
pytest-benchmark[dev,test]
tox[dev]
black[dev]
isort[dev]
flake8[dev]
bandit[dev]
towncrier[dev]
sphinx[doc]>=2.1.2
sphinx_rtd_theme[doc]
recommonmark[doc]>=0.5.0
docutils[doc]
pygments[doc]
```

**Comment by ahopkins** [comment]
How well does it play with tox?

**Comment by ChihweiLHBird** [comment]
> How well does it play with tox?

I only got Python 3.8 installed so tox didn't find other versions of Python. Is it necessary (or recommended) to install all of them and test it locally?

My environment for running it was Ubuntu WSL2 (Windows Subsystem for Linux 2).

```
______________________________________________________________________________________________ summary ______________________________________________________________________________________________
ERROR:  py37: InterpreterNotFound: python3.7
  py38: commands succeeded
ERROR:  py39: InterpreterNotFound: python3.9
  pyNightly: commands succeeded
ERROR:  pypy37: InterpreterNotFound: pypy3.7
ERROR:  py37-no-ext: InterpreterNotFound: python3.7
ERROR:   py38-no-ext: commands failed
ERROR:  py39-no-ext: InterpreterNotFound: python3.9
  pyNightly-no-ext: commands succeeded
ERROR:  pypy37-no-ext: InterpreterNotFound: pypy3.7
  lint: commands succeeded
  check: commands succeeded
  security: commands succeeded
  docs: commands succeeded
  type-checking: commands succeeded
```

**Comment by ChihweiLHBird** [comment]
> > How well does it play with tox?
> 
> I only got Python 3.8 installed so tox didn't find other versions of Python. Is it necessary (or recommended) to install all of them and test it locally?
> 
> My environment for running it was Ubuntu WSL2 (Windows Subsystem for Linux 2).
> 
> ```
> ______________________________________________________________________________________________ summary ______________________________________________________________________________________________
> ERROR:  py37: InterpreterNotFound: python3.7
>   py38: commands succeeded
> ERROR:  py39: InterpreterNotFound: python3.9
>   pyNightly: commands succeeded
> ERROR:  pypy37: InterpreterNotFound: pypy3.7
> ERROR:  py37-no-ext: InterpreterNotFound: python3.7
> ERROR:   py38-no-ext: commands failed
> ERROR:  py39-no-ext: InterpreterNotFound: python3.9
>   pyNightly-no-ext: commands succeeded
> ERROR:  pypy37-no-ext: InterpreterNotFound: pypy3.7
>   lint: commands succeeded
>   check: commands succeeded
>   security: commands succeeded
>   docs: commands succeeded
>   type-checking: commands succeeded
> ```

Ran it again and py38-no-ext became success... Not sure why.

```
___________________________________ summary ____________________________________
ERROR:  py37: InterpreterNotFound: python3.7
  py38: commands succeeded
ERROR:  py39: InterpreterNotFound: python3.9
  pyNightly: commands succeeded
ERROR:  pypy37: InterpreterNotFound: pypy3.7
ERROR:  py37-no-ext: InterpreterNotFound: python3.7
  py38-no-ext: commands succeeded
ERROR:  py39-no-ext: InterpreterNotFound: python3.9
  pyNightly-no-ext: commands succeeded
ERROR:  pypy37-no-ext: InterpreterNotFound: pypy3.7
  lint: commands succeeded
  check: commands succeeded
  security: commands succeeded
  docs: commands succeeded
  type-checking: commands succeeded
```

**Comment by ChihweiLHBird** [comment]
The error was:
```
=================================== FAILURES ===================================
________________________ test_keep_alive_client_timeout ________________________

    @pytest.mark.skipif(
        bool(environ.get("SANIC_NO_UVLOOP"))
        or OS_IS_WINDOWS
        or platform.system() != "Linux",
        reason="Not testable with current client",
    )
    def test_keep_alive_client_timeout():
        """If the server keep-alive timeout is longer than the client
        keep-alive timeout, client will try to create a new connection here."""
        try:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            client = ReuseableSanicTestClient(keep_alive_app_client_timeout, loop)
            headers = {"Connection": "keep-alive"}
            _, response = client.get("/1", headers=headers, request_keepalive=1)
    
            assert response.status == 200
            assert response.text == "OK"
    
            loop.run_until_complete(aio_sleep(2))
            _, response = client.get("/1", request_keepalive=1)
    
>           assert ReusableSanicConnectionPool.last_reused_connection is None
E           assert <AsyncHTTPConnection [HTTP/1.1, IDLE]> is None
E            +  where <AsyncHTTPConnection [HTTP/1.1, IDLE]> = ReusableSanicConnectionPool.last_reused_connection
```

**Comment by ahopkins** [comment]
> I only got Python 3.8 installed so tox didn't find other versions of Python. Is it necessary (or recommended) to install all of them and test it locally?

Nope, that's what CI id for :sunglasses:  

> I don't know how it is related my change, but since the second run is okay, I guess it is a random fail.

That test is sometimes a bit flappy. Testing the keep-alive is a bit tricky. I don't read much into that failure.

**Comment by ChihweiLHBird** [comment]
> > I only got Python 3.8 installed so tox didn't find other versions of Python. Is it necessary (or recommended) to install all of them and test it locally?
> 
> Nope, that's what CI is for 😎
> 
> > I don't know how it is related my change, but since the second run is okay, I guess it is a random fail.
> 
> That test is sometimes a bit flappy. Testing the keep-alive is a bit tricky. I don't read much into that failure.

Thank you! So do you think we can merge these change? Is there anything that can be improved?

**Comment by ahopkins** [comment]
> Thank you! So do you think we can merge these change? Is there anything that can be improved?

I think the last thing that really might be helpful is cleanup for tox since these are duplicated there. Something like this:

```
deps = .[test]
```

We then could duplicate the pattern for `lint`, `docs`, etc on the other tox environments. so that there is no more list of deps in tox also.

See: https://stackoverflow.com/a/41398850/1036843

**Comment by ChihweiLHBird** [comment]
> > Thank you! So do you think we can merge these change? Is there anything that can be improved?
> 
> I think the last thing that really might be helpful is cleanup for tox since these are duplicated there. Something like this:
> 
> ```
> deps = .[test]
> ```
> 
> We then could duplicate the pattern for `lint`, `docs`, etc on the other tox environments. so that there is no more list of deps in tox also.
> 
> See: https://stackoverflow.com/a/41398850/1036843

Thank you @ahopkins , let me take a look at that. There are some deps which are in `tox.ini` but not in `setup.py`'s test extras requirements list. I think I would need to add them in `setup.py`.

**Comment by ChihweiLHBird** [comment]
@ahopkins Do we have any specific reason to set `usedevelop` to `True` in `tox.ini`? I found this option may cause the problem that dependencies won't be installed in some Python versions, if I let tox read extras dependencies from `setup.py`. I am wondering if I may remove this option.

**Comment by ChihweiLHBird** [comment]
Local tox output, seems successful.
```
___________________________________ summary ____________________________________
ERROR:  py37: InterpreterNotFound: python3.7
  py38: commands succeeded
ERROR:  py39: InterpreterNotFound: python3.9
  pyNightly: commands succeeded
ERROR:  pypy37: InterpreterNotFound: pypy3.7
ERROR:  py37-no-ext: InterpreterNotFound: python3.7
  py38-no-ext: commands succeeded
ERROR:  py39-no-ext: InterpreterNotFound: python3.9
  pyNightly-no-ext: commands succeeded
ERROR:  pypy37-no-ext: InterpreterNotFound: pypy3.7
  lint: commands succeeded
  check: commands succeeded
  security: commands succeeded
  docs: commands succeeded
  type-checking: commands succeeded
```
https://1drv.ms/t/s!Auf8Km0xmwewhflpgKbHeKHv2yipag?e=C3bFXg

**Comment by ahopkins** [comment]
> @ahopkins Do we have any specific reason to set `usedevelop` to `True` in `tox.ini`? I found this option may cause the problem that dependencies won't be installed in some Python versions, if I let tox read extras dependencies from `setup.py`. I am wondering if I may remove this option.

it's the same as using `-e`. if it runs without it, then remove it.

**Comment by ChihweiLHBird** [comment]
> > @ahopkins Do we have any specific reason to set `usedevelop` to `True` in `tox.ini`? I found this option may cause the problem that dependencies won't be installed in some Python versions, if I let tox read extras dependencies from `setup.py`. I am wondering if I may remove this option.
> 
> it's the same as using `-e`. if it runs without it, then remove it.

@ahopkins Thank you! I think everything is good now. Can you trigger the CI and review this PR?

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
