### PR TITLE
Fixed `mixins.startup.serve` UnboundLocalError.

### PR DESCRIPTION
**Pull request by pygeek**
Fixes https://github.com/sanic-org/sanic/issues/2985

the `finally` block in `mixins.serve` references a variable that is only defined in the `try` block. This results in a `UnboundLocalError` within the `finally` block.

### CODE REVIEW

**Comment by pygeek** [comment]
There do not seem to be existing tests that specifically test the functionality of `mixins.startup.serve`, nor the `startup` module overall.

**Comment by pygeek** [comment]
Type error being raised by CI by line 724 of `mixins.startup` existed prior to my changes.

**Comment by ahopkins** [comment]
How did you come by this error?

**Comment by prryplatypus** [comment]
> How did you come by this error?

There seems to be a repro in the linked issue (I haven't tested it)

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
