### PR TITLE
(20.12 LTS backport) fix request.args.pop removing parameters inconsistently 

### PR DESCRIPTION
**Pull request by artcg**

### CODE REVIEW

**Comment by ahopkins** [comment]
See #2106 and #2110

**Comment by ashleysommer** [comment]
Looks good.
Is there any other recent fixes from 21.3 or master that we should push back into 20.12 to make a new LTS release?

**Comment by ahopkins** [comment]
None. Since this has been out there for at least 2 years, my thought was to roll LTS updates with the next release.

**Comment by ashleysommer** [comment]
Submitter confirmed that https://github.com/sanic-org/sanic/issues/2113 affects 20.12 too, so when a fix for that comes we should roll that into LTS too.

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
