### PR TITLE
Upgrade websockets dependency.

### LINKED ISSUE #2142: Allow later websockets releases
**Describe the bug**
`websockets` is [pinned](https://github.com/sanic-org/sanic/blob/main/setup.py#L91
). The latest `websockets` is 9.1 and this release is fixing a [authentication vulnerability](https://websockets.readthedocs.io/en/stable/changelog.html) which was introduced with 8.0.

**Expected behavior**
Allow to use `websockets>9`

**Environment (please complete the following information):**
 - OS: probably all
 - Version: current

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by aaugustin**
Fix #2142.

### CODE REVIEW

**Review by ahopkins — DISMISSED** [review]
Thanks @aaugustin 

If this is all we need for 9 support, then maybe the answer for #2000 is to hold off on inclusion of the sans-io implementation until our September release.

@ashleysommer?

**Comment by aaugustin** [comment]
From my perspective as the maintainer of websockets, you can happily live with this for a few years :-)

I just need to get the checks to pass!

**Comment by ahopkins** [comment]
> I just need to get the checks to pass!

I am pulling locally and will push a commit for the linting

**Comment by aaugustin** [comment]
I tried to fix it in the meantime. I'll stop interfering now and leave it up to you!

**Comment by ahopkins** [comment]
No worries. I was trying to make it easier for you. It should be as simple as `make pretty` assuming you have black and isort installed. Will wait for the checks to run.

Thanks again for your help and support.

**Review by ahopkins — APPROVED** [review]

**Comment by ahopkins** [comment]
:unamused: So, I cannot seem to get the tests to build unless I use `--use-deprecated=legacy-resolver`.

This seems odd to me, since it seems like `websockets` has no external dependencies, correct?

**Comment by ahopkins** [comment]
I am going to have to hold off on merging this one until I do a release of `sanic-testing` to get the websockets v8 req lifted. I _think_ that is why the tests are ending up in resolution hell.

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
