### PR TITLE
Resolve regressions in exceptions

### LINKED ISSUE #2177: asyncio.exceptions.CancelledError On Windows OS
The following exception raised when running the hello world example on Windows with Microsoft store version of Python 3.9.

WSL2 environment does not reproduce the issue.

```
from sanic import Sanic
from sanic.response import json

app = Sanic("My Hello, world app")

@app.route('/')
async def test(request):
    return json({'hello': 'world'})

if __name__ == '__main__':
    app.run()
```

```
[2021-06-30 23:00:05 -0700] [12184] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2021-06-30 23:00:06 -0700] [12184] [INFO] Starting worker [12184]
[2021-06-30 23:00:11 -0700] - (sanic.access)[INFO][127.0.0.1:53159]: GET http://127.0.0.1:8000/  200 17
[2021-06-30 23:01:11 -0700] [12184] [ERROR] Exception occurred while handling uri: 'http:///*'
Traceback (most recent call last):
  File "C:\Users\zhiwe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sanic\http.py", line 126, in http1
    await self.http1_request_header()
  File "C:\Users\zhiwe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sanic\http.py", line 188, in http1_request_header      
    await self._receive_more()
  File "C:\Users\zhiwe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sanic\server.py", line 222, in receive_more
    await self._data_received.wait()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError
[2021-06-30 23:01:11 -0700] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  408 664
```

### PR DESCRIPTION
**Pull request by ahopkins**
Resolve #2177 

When we merged #2077, the default `quiet` attribute was not being set properly. This restores quiet to the pre-2077 values.

### CODE REVIEW

**Review by Tronic — DISMISSED** [review]

**Comment by robd003** [comment]
Can we get all of the approved (but not yet merged) pull requests in this next release too?

**Comment by ahopkins** [comment]
> Can we get all of the approved (but not yet merged) pull requests in this next release too?

Like what specifically? Usually we only post release bug fixes.

**Comment by robd003** [comment]
https://github.com/sanic-org/sanic/pull/2178
https://github.com/sanic-org/sanic/pull/2179

**Comment by ahopkins** [comment]
#2178 yes. #2179 no.

**Review by seemethere — APPROVED** [review]

**Pull request merged**
